title: Blog BAIN
author: Lisa Oehler
email: /
description: > # this means to ignore newlines
  Lerntagebuch im Kurs Bibliotheks- und Archivinformatik HS2021



show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
